root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  full_bin = "./tmp/server"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "vendor", "proto"]

[log]
  time = false
