run:
  timeout: 5m
  tests: true
linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
linters-settings:
  staticcheck:
    checks: ["all"]
issues:
  exclude-dirs:
    - proto
    - third_party
  exclude-files:
    - ".*\\.pb\\.go$"
