// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: audit/v1/audit_service.proto

package auditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_ListAuditEntries_FullMethodName = "/schemahub.audit.v1.AuditService/ListAuditEntries"
	AuditService_GetAuditEntry_FullMethodName    = "/schemahub.audit.v1.AuditService/GetAuditEntry"
	AuditService_TailAuditEntries_FullMethodName = "/schemahub.audit.v1.AuditService/TailAuditEntries"
	AuditService_GetAuditStats_FullMethodName    = "/schemahub.audit.v1.AuditService/GetAuditStats"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	ListAuditEntries(ctx context.Context, in *ListAuditEntriesRequest, opts ...grpc.CallOption) (*ListAuditEntriesResponse, error)
	GetAuditEntry(ctx context.Context, in *GetAuditEntryRequest, opts ...grpc.CallOption) (*GetAuditEntryResponse, error)
	TailAuditEntries(ctx context.Context, in *TailAuditEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEntry], error)
	GetAuditStats(ctx context.Context, in *GetAuditStatsRequest, opts ...grpc.CallOption) (*GetAuditStatsResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) ListAuditEntries(ctx context.Context, in *ListAuditEntriesRequest, opts ...grpc.CallOption) (*ListAuditEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEntriesResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetAuditEntry(ctx context.Context, in *GetAuditEntryRequest, opts ...grpc.CallOption) (*GetAuditEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditEntryResponse)
	err := c.cc.Invoke(ctx, AuditService_GetAuditEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) TailAuditEntries(ctx context.Context, in *TailAuditEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuditService_ServiceDesc.Streams[0], AuditService_TailAuditEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TailAuditEntriesRequest, AuditEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditService_TailAuditEntriesClient = grpc.ServerStreamingClient[AuditEntry]

func (c *auditServiceClient) GetAuditStats(ctx context.Context, in *GetAuditStatsRequest, opts ...grpc.CallOption) (*GetAuditStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditStatsResponse)
	err := c.cc.Invoke(ctx, AuditService_GetAuditStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	ListAuditEntries(context.Context, *ListAuditEntriesRequest) (*ListAuditEntriesResponse, error)
	GetAuditEntry(context.Context, *GetAuditEntryRequest) (*GetAuditEntryResponse, error)
	TailAuditEntries(*TailAuditEntriesRequest, grpc.ServerStreamingServer[AuditEntry]) error
	GetAuditStats(context.Context, *GetAuditStatsRequest) (*GetAuditStatsResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) ListAuditEntries(context.Context, *ListAuditEntriesRequest) (*ListAuditEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEntries not implemented")
}
func (UnimplementedAuditServiceServer) GetAuditEntry(context.Context, *GetAuditEntryRequest) (*GetAuditEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditEntry not implemented")
}
func (UnimplementedAuditServiceServer) TailAuditEntries(*TailAuditEntriesRequest, grpc.ServerStreamingServer[AuditEntry]) error {
	return status.Error(codes.Unimplemented, "method TailAuditEntries not implemented")
}
func (UnimplementedAuditServiceServer) GetAuditStats(context.Context, *GetAuditStatsRequest) (*GetAuditStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditStats not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_ListAuditEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditEntries(ctx, req.(*ListAuditEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetAuditEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetAuditEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetAuditEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetAuditEntry(ctx, req.(*GetAuditEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_TailAuditEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailAuditEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuditServiceServer).TailAuditEntries(m, &grpc.GenericServerStream[TailAuditEntriesRequest, AuditEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditService_TailAuditEntriesServer = grpc.ServerStreamingServer[AuditEntry]

func _AuditService_GetAuditStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetAuditStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetAuditStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetAuditStats(ctx, req.(*GetAuditStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schemahub.audit.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAuditEntries",
			Handler:    _AuditService_ListAuditEntries_Handler,
		},
		{
			MethodName: "GetAuditEntry",
			Handler:    _AuditService_GetAuditEntry_Handler,
		},
		{
			MethodName: "GetAuditStats",
			Handler:    _AuditService_GetAuditStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TailAuditEntries",
			Handler:       _AuditService_TailAuditEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "audit/v1/audit_service.proto",
}
