// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: migration/v1/migration_service.proto

package migrationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MigrationService_CreateMigration_FullMethodName   = "/schemahub.migration.v1.MigrationService/CreateMigration"
	MigrationService_GetMigration_FullMethodName      = "/schemahub.migration.v1.MigrationService/GetMigration"
	MigrationService_ListMigrations_FullMethodName    = "/schemahub.migration.v1.MigrationService/ListMigrations"
	MigrationService_UpdateMigration_FullMethodName   = "/schemahub.migration.v1.MigrationService/UpdateMigration"
	MigrationService_DeleteMigration_FullMethodName   = "/schemahub.migration.v1.MigrationService/DeleteMigration"
	MigrationService_ExecuteMigration_FullMethodName  = "/schemahub.migration.v1.MigrationService/ExecuteMigration"
	MigrationService_WatchMigration_FullMethodName    = "/schemahub.migration.v1.MigrationService/WatchMigration"
	MigrationService_RollbackMigration_FullMethodName = "/schemahub.migration.v1.MigrationService/RollbackMigration"
	MigrationService_WatchRollback_FullMethodName     = "/schemahub.migration.v1.MigrationService/WatchRollback"
	MigrationService_ValidateMigration_FullMethodName = "/schemahub.migration.v1.MigrationService/ValidateMigration"
	MigrationService_DryRunMigration_FullMethodName   = "/schemahub.migration.v1.MigrationService/DryRunMigration"
	MigrationService_GetMigrationRun_FullMethodName   = "/schemahub.migration.v1.MigrationService/GetMigrationRun"
	MigrationService_ListMigrationRuns_FullMethodName = "/schemahub.migration.v1.MigrationService/ListMigrationRuns"
	MigrationService_GetMigrationLogs_FullMethodName  = "/schemahub.migration.v1.MigrationService/GetMigrationLogs"
)

// MigrationServiceClient is the client API for MigrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrationServiceClient interface {
	CreateMigration(ctx context.Context, in *CreateMigrationRequest, opts ...grpc.CallOption) (*CreateMigrationResponse, error)
	GetMigration(ctx context.Context, in *GetMigrationRequest, opts ...grpc.CallOption) (*GetMigrationResponse, error)
	ListMigrations(ctx context.Context, in *ListMigrationsRequest, opts ...grpc.CallOption) (*ListMigrationsResponse, error)
	UpdateMigration(ctx context.Context, in *UpdateMigrationRequest, opts ...grpc.CallOption) (*UpdateMigrationResponse, error)
	DeleteMigration(ctx context.Context, in *DeleteMigrationRequest, opts ...grpc.CallOption) (*DeleteMigrationResponse, error)
	ExecuteMigration(ctx context.Context, in *ExecuteMigrationRequest, opts ...grpc.CallOption) (*ExecuteMigrationResponse, error)
	WatchMigration(ctx context.Context, in *WatchMigrationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationStatusMessage], error)
	RollbackMigration(ctx context.Context, in *RollbackMigrationRequest, opts ...grpc.CallOption) (*RollbackMigrationResponse, error)
	WatchRollback(ctx context.Context, in *WatchRollbackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationStatusMessage], error)
	ValidateMigration(ctx context.Context, in *ValidateMigrationRequest, opts ...grpc.CallOption) (*ValidateMigrationResponse, error)
	DryRunMigration(ctx context.Context, in *DryRunMigrationRequest, opts ...grpc.CallOption) (*DryRunMigrationResponse, error)
	GetMigrationRun(ctx context.Context, in *GetMigrationRunRequest, opts ...grpc.CallOption) (*GetMigrationRunResponse, error)
	ListMigrationRuns(ctx context.Context, in *ListMigrationRunsRequest, opts ...grpc.CallOption) (*ListMigrationRunsResponse, error)
	GetMigrationLogs(ctx context.Context, in *GetMigrationLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationLogEntry], error)
}

type migrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrationServiceClient(cc grpc.ClientConnInterface) MigrationServiceClient {
	return &migrationServiceClient{cc}
}

func (c *migrationServiceClient) CreateMigration(ctx context.Context, in *CreateMigrationRequest, opts ...grpc.CallOption) (*CreateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_CreateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) GetMigration(ctx context.Context, in *GetMigrationRequest, opts ...grpc.CallOption) (*GetMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_GetMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) ListMigrations(ctx context.Context, in *ListMigrationsRequest, opts ...grpc.CallOption) (*ListMigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMigrationsResponse)
	err := c.cc.Invoke(ctx, MigrationService_ListMigrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) UpdateMigration(ctx context.Context, in *UpdateMigrationRequest, opts ...grpc.CallOption) (*UpdateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_UpdateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) DeleteMigration(ctx context.Context, in *DeleteMigrationRequest, opts ...grpc.CallOption) (*DeleteMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_DeleteMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) ExecuteMigration(ctx context.Context, in *ExecuteMigrationRequest, opts ...grpc.CallOption) (*ExecuteMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_ExecuteMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) WatchMigration(ctx context.Context, in *WatchMigrationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationStatusMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MigrationService_ServiceDesc.Streams[0], MigrationService_WatchMigration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchMigrationRequest, MigrationStatusMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationService_WatchMigrationClient = grpc.ServerStreamingClient[MigrationStatusMessage]

func (c *migrationServiceClient) RollbackMigration(ctx context.Context, in *RollbackMigrationRequest, opts ...grpc.CallOption) (*RollbackMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_RollbackMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) WatchRollback(ctx context.Context, in *WatchRollbackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationStatusMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MigrationService_ServiceDesc.Streams[1], MigrationService_WatchRollback_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRollbackRequest, MigrationStatusMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationService_WatchRollbackClient = grpc.ServerStreamingClient[MigrationStatusMessage]

func (c *migrationServiceClient) ValidateMigration(ctx context.Context, in *ValidateMigrationRequest, opts ...grpc.CallOption) (*ValidateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_ValidateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) DryRunMigration(ctx context.Context, in *DryRunMigrationRequest, opts ...grpc.CallOption) (*DryRunMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DryRunMigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_DryRunMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) GetMigrationRun(ctx context.Context, in *GetMigrationRunRequest, opts ...grpc.CallOption) (*GetMigrationRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMigrationRunResponse)
	err := c.cc.Invoke(ctx, MigrationService_GetMigrationRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) ListMigrationRuns(ctx context.Context, in *ListMigrationRunsRequest, opts ...grpc.CallOption) (*ListMigrationRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMigrationRunsResponse)
	err := c.cc.Invoke(ctx, MigrationService_ListMigrationRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) GetMigrationLogs(ctx context.Context, in *GetMigrationLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationLogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MigrationService_ServiceDesc.Streams[2], MigrationService_GetMigrationLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMigrationLogsRequest, MigrationLogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationService_GetMigrationLogsClient = grpc.ServerStreamingClient[MigrationLogEntry]

// MigrationServiceServer is the server API for MigrationService service.
// All implementations must embed UnimplementedMigrationServiceServer
// for forward compatibility.
type MigrationServiceServer interface {
	CreateMigration(context.Context, *CreateMigrationRequest) (*CreateMigrationResponse, error)
	GetMigration(context.Context, *GetMigrationRequest) (*GetMigrationResponse, error)
	ListMigrations(context.Context, *ListMigrationsRequest) (*ListMigrationsResponse, error)
	UpdateMigration(context.Context, *UpdateMigrationRequest) (*UpdateMigrationResponse, error)
	DeleteMigration(context.Context, *DeleteMigrationRequest) (*DeleteMigrationResponse, error)
	ExecuteMigration(context.Context, *ExecuteMigrationRequest) (*ExecuteMigrationResponse, error)
	WatchMigration(*WatchMigrationRequest, grpc.ServerStreamingServer[MigrationStatusMessage]) error
	RollbackMigration(context.Context, *RollbackMigrationRequest) (*RollbackMigrationResponse, error)
	WatchRollback(*WatchRollbackRequest, grpc.ServerStreamingServer[MigrationStatusMessage]) error
	ValidateMigration(context.Context, *ValidateMigrationRequest) (*ValidateMigrationResponse, error)
	DryRunMigration(context.Context, *DryRunMigrationRequest) (*DryRunMigrationResponse, error)
	GetMigrationRun(context.Context, *GetMigrationRunRequest) (*GetMigrationRunResponse, error)
	ListMigrationRuns(context.Context, *ListMigrationRunsRequest) (*ListMigrationRunsResponse, error)
	GetMigrationLogs(*GetMigrationLogsRequest, grpc.ServerStreamingServer[MigrationLogEntry]) error
	mustEmbedUnimplementedMigrationServiceServer()
}

// UnimplementedMigrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigrationServiceServer struct{}

func (UnimplementedMigrationServiceServer) CreateMigration(context.Context, *CreateMigrationRequest) (*CreateMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMigration not implemented")
}
func (UnimplementedMigrationServiceServer) GetMigration(context.Context, *GetMigrationRequest) (*GetMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMigration not implemented")
}
func (UnimplementedMigrationServiceServer) ListMigrations(context.Context, *ListMigrationsRequest) (*ListMigrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMigrations not implemented")
}
func (UnimplementedMigrationServiceServer) UpdateMigration(context.Context, *UpdateMigrationRequest) (*UpdateMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMigration not implemented")
}
func (UnimplementedMigrationServiceServer) DeleteMigration(context.Context, *DeleteMigrationRequest) (*DeleteMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMigration not implemented")
}
func (UnimplementedMigrationServiceServer) ExecuteMigration(context.Context, *ExecuteMigrationRequest) (*ExecuteMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteMigration not implemented")
}
func (UnimplementedMigrationServiceServer) WatchMigration(*WatchMigrationRequest, grpc.ServerStreamingServer[MigrationStatusMessage]) error {
	return status.Error(codes.Unimplemented, "method WatchMigration not implemented")
}
func (UnimplementedMigrationServiceServer) RollbackMigration(context.Context, *RollbackMigrationRequest) (*RollbackMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackMigration not implemented")
}
func (UnimplementedMigrationServiceServer) WatchRollback(*WatchRollbackRequest, grpc.ServerStreamingServer[MigrationStatusMessage]) error {
	return status.Error(codes.Unimplemented, "method WatchRollback not implemented")
}
func (UnimplementedMigrationServiceServer) ValidateMigration(context.Context, *ValidateMigrationRequest) (*ValidateMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateMigration not implemented")
}
func (UnimplementedMigrationServiceServer) DryRunMigration(context.Context, *DryRunMigrationRequest) (*DryRunMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRunMigration not implemented")
}
func (UnimplementedMigrationServiceServer) GetMigrationRun(context.Context, *GetMigrationRunRequest) (*GetMigrationRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMigrationRun not implemented")
}
func (UnimplementedMigrationServiceServer) ListMigrationRuns(context.Context, *ListMigrationRunsRequest) (*ListMigrationRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMigrationRuns not implemented")
}
func (UnimplementedMigrationServiceServer) GetMigrationLogs(*GetMigrationLogsRequest, grpc.ServerStreamingServer[MigrationLogEntry]) error {
	return status.Error(codes.Unimplemented, "method GetMigrationLogs not implemented")
}
func (UnimplementedMigrationServiceServer) mustEmbedUnimplementedMigrationServiceServer() {}
func (UnimplementedMigrationServiceServer) testEmbeddedByValue()                          {}

// UnsafeMigrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrationServiceServer will
// result in compilation errors.
type UnsafeMigrationServiceServer interface {
	mustEmbedUnimplementedMigrationServiceServer()
}

func RegisterMigrationServiceServer(s grpc.ServiceRegistrar, srv MigrationServiceServer) {
	// If the following call panics, it indicates UnimplementedMigrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MigrationService_ServiceDesc, srv)
}

func _MigrationService_CreateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).CreateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_CreateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).CreateMigration(ctx, req.(*CreateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_GetMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).GetMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_GetMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).GetMigration(ctx, req.(*GetMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_ListMigrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).ListMigrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_ListMigrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).ListMigrations(ctx, req.(*ListMigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_UpdateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).UpdateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_UpdateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).UpdateMigration(ctx, req.(*UpdateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_DeleteMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).DeleteMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_DeleteMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).DeleteMigration(ctx, req.(*DeleteMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_ExecuteMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).ExecuteMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_ExecuteMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).ExecuteMigration(ctx, req.(*ExecuteMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_WatchMigration_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMigrationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MigrationServiceServer).WatchMigration(m, &grpc.GenericServerStream[WatchMigrationRequest, MigrationStatusMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationService_WatchMigrationServer = grpc.ServerStreamingServer[MigrationStatusMessage]

func _MigrationService_RollbackMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).RollbackMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_RollbackMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).RollbackMigration(ctx, req.(*RollbackMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_WatchRollback_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRollbackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MigrationServiceServer).WatchRollback(m, &grpc.GenericServerStream[WatchRollbackRequest, MigrationStatusMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationService_WatchRollbackServer = grpc.ServerStreamingServer[MigrationStatusMessage]

func _MigrationService_ValidateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).ValidateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_ValidateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).ValidateMigration(ctx, req.(*ValidateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_DryRunMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DryRunMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).DryRunMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_DryRunMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).DryRunMigration(ctx, req.(*DryRunMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_GetMigrationRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMigrationRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).GetMigrationRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_GetMigrationRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).GetMigrationRun(ctx, req.(*GetMigrationRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_ListMigrationRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMigrationRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).ListMigrationRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_ListMigrationRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).ListMigrationRuns(ctx, req.(*ListMigrationRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_GetMigrationLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMigrationLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MigrationServiceServer).GetMigrationLogs(m, &grpc.GenericServerStream[GetMigrationLogsRequest, MigrationLogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationService_GetMigrationLogsServer = grpc.ServerStreamingServer[MigrationLogEntry]

// MigrationService_ServiceDesc is the grpc.ServiceDesc for MigrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MigrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schemahub.migration.v1.MigrationService",
	HandlerType: (*MigrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMigration",
			Handler:    _MigrationService_CreateMigration_Handler,
		},
		{
			MethodName: "GetMigration",
			Handler:    _MigrationService_GetMigration_Handler,
		},
		{
			MethodName: "ListMigrations",
			Handler:    _MigrationService_ListMigrations_Handler,
		},
		{
			MethodName: "UpdateMigration",
			Handler:    _MigrationService_UpdateMigration_Handler,
		},
		{
			MethodName: "DeleteMigration",
			Handler:    _MigrationService_DeleteMigration_Handler,
		},
		{
			MethodName: "ExecuteMigration",
			Handler:    _MigrationService_ExecuteMigration_Handler,
		},
		{
			MethodName: "RollbackMigration",
			Handler:    _MigrationService_RollbackMigration_Handler,
		},
		{
			MethodName: "ValidateMigration",
			Handler:    _MigrationService_ValidateMigration_Handler,
		},
		{
			MethodName: "DryRunMigration",
			Handler:    _MigrationService_DryRunMigration_Handler,
		},
		{
			MethodName: "GetMigrationRun",
			Handler:    _MigrationService_GetMigrationRun_Handler,
		},
		{
			MethodName: "ListMigrationRuns",
			Handler:    _MigrationService_ListMigrationRuns_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMigration",
			Handler:       _MigrationService_WatchMigration_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchRollback",
			Handler:       _MigrationService_WatchRollback_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetMigrationLogs",
			Handler:       _MigrationService_GetMigrationLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "migration/v1/migration_service.proto",
}
