// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: migration/v1/migration_messages.proto

package migrationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Migration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId   string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Version     string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	UpSql       string `protobuf:"bytes,6,opt,name=up_sql,json=upSql,proto3" json:"up_sql,omitempty"`
	DownSql     string `protobuf:"bytes,7,opt,name=down_sql,json=downSql,proto3" json:"down_sql,omitempty"`
	Checksum    string `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Status      string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy   string `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt   string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Migration) Reset() {
	*x = Migration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Migration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Migration) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Migration) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Migration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Migration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Migration) GetUpSql() string {
	if x != nil {
		return x.UpSql
	}
	return ""
}

func (x *Migration) GetDownSql() string {
	if x != nil {
		return x.DownSql
	}
	return ""
}

func (x *Migration) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Migration) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Migration) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Migration) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Migration) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MigrationRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MigrationId  string `protobuf:"bytes,2,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	ConnectionId string `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Direction    string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Status       string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt    string `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt  string `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs   int32  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ErrorMessage string `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExecutedBy   string `protobuf:"bytes,10,opt,name=executed_by,json=executedBy,proto3" json:"executed_by,omitempty"`
	CreatedAt    string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *MigrationRun) Reset() {
	*x = MigrationRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRun) ProtoMessage() {}

func (x *MigrationRun) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRun.ProtoReflect.Descriptor instead.
func (*MigrationRun) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MigrationRun) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *MigrationRun) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *MigrationRun) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *MigrationRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MigrationRun) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *MigrationRun) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *MigrationRun) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MigrationRun) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MigrationRun) GetExecutedBy() string {
	if x != nil {
		return x.ExecutedBy
	}
	return ""
}

func (x *MigrationRun) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MigrationLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence     int32  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Sql          string `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	DurationMs   int32  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RowsAffected int32  `protobuf:"varint,4,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt    string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *MigrationLogEntry) Reset() {
	*x = MigrationLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationLogEntry) ProtoMessage() {}

func (x *MigrationLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationLogEntry.ProtoReflect.Descriptor instead.
func (*MigrationLogEntry) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MigrationLogEntry) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MigrationLogEntry) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *MigrationLogEntry) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MigrationLogEntry) GetRowsAffected() int32 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *MigrationLogEntry) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MigrationLogEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MigrationStatusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId               string             `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	State               string             `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	TotalStatements     int32              `protobuf:"varint,3,opt,name=total_statements,json=totalStatements,proto3" json:"total_statements,omitempty"`
	CompletedStatements int32              `protobuf:"varint,4,opt,name=completed_statements,json=completedStatements,proto3" json:"completed_statements,omitempty"`
	CurrentStatement    string             `protobuf:"bytes,5,opt,name=current_statement,json=currentStatement,proto3" json:"current_statement,omitempty"`
	StartedAt           string             `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ElapsedMs           int64              `protobuf:"varint,7,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	ErrorMessage        string             `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LastLog             *MigrationLogEntry `protobuf:"bytes,9,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
}

func (x *MigrationStatusMessage) Reset() {
	*x = MigrationStatusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStatusMessage) ProtoMessage() {}

func (x *MigrationStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStatusMessage.ProtoReflect.Descriptor instead.
func (*MigrationStatusMessage) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MigrationStatusMessage) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *MigrationStatusMessage) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MigrationStatusMessage) GetTotalStatements() int32 {
	if x != nil {
		return x.TotalStatements
	}
	return 0
}

func (x *MigrationStatusMessage) GetCompletedStatements() int32 {
	if x != nil {
		return x.CompletedStatements
	}
	return 0
}

func (x *MigrationStatusMessage) GetCurrentStatement() string {
	if x != nil {
		return x.CurrentStatement
	}
	return ""
}

func (x *MigrationStatusMessage) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *MigrationStatusMessage) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *MigrationStatusMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MigrationStatusMessage) GetLastLog() *MigrationLogEntry {
	if x != nil {
		return x.LastLog
	}
	return nil
}

type CreateMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId   string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UpSql       string `protobuf:"bytes,4,opt,name=up_sql,json=upSql,proto3" json:"up_sql,omitempty"`
	DownSql     string `protobuf:"bytes,5,opt,name=down_sql,json=downSql,proto3" json:"down_sql,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateMigrationRequest) Reset() {
	*x = CreateMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationRequest) ProtoMessage() {}

func (x *CreateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationRequest.ProtoReflect.Descriptor instead.
func (*CreateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMigrationRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateMigrationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMigrationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateMigrationRequest) GetUpSql() string {
	if x != nil {
		return x.UpSql
	}
	return ""
}

func (x *CreateMigrationRequest) GetDownSql() string {
	if x != nil {
		return x.DownSql
	}
	return ""
}

func (x *CreateMigrationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Migration *Migration `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
}

func (x *CreateMigrationResponse) Reset() {
	*x = CreateMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationResponse) ProtoMessage() {}

func (x *CreateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationResponse.ProtoReflect.Descriptor instead.
func (*CreateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type GetMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMigrationRequest) Reset() {
	*x = GetMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationRequest) ProtoMessage() {}

func (x *GetMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetMigrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Migration *Migration `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
}

func (x *GetMigrationResponse) Reset() {
	*x = GetMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationResponse) ProtoMessage() {}

func (x *GetMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type ListMigrationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Cursor    string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize  int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListMigrationsRequest) Reset() {
	*x = ListMigrationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsRequest) ProtoMessage() {}

func (x *ListMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsRequest.ProtoReflect.Descriptor instead.
func (*ListMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ListMigrationsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListMigrationsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMigrationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMigrationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Migrations []*Migration `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	NextCursor string       `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	TotalCount int32        `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListMigrationsResponse) Reset() {
	*x = ListMigrationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsResponse) ProtoMessage() {}

func (x *ListMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsResponse.ProtoReflect.Descriptor instead.
func (*ListMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ListMigrationsResponse) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

func (x *ListMigrationsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListMigrationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	UpSql       *string `protobuf:"bytes,4,opt,name=up_sql,json=upSql,proto3,oneof" json:"up_sql,omitempty"`
	DownSql     *string `protobuf:"bytes,5,opt,name=down_sql,json=downSql,proto3,oneof" json:"down_sql,omitempty"`
	Status      *string `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *UpdateMigrationRequest) Reset() {
	*x = UpdateMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMigrationRequest) ProtoMessage() {}

func (x *UpdateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMigrationRequest.ProtoReflect.Descriptor instead.
func (*UpdateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMigrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMigrationRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateMigrationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMigrationRequest) GetUpSql() string {
	if x != nil && x.UpSql != nil {
		return *x.UpSql
	}
	return ""
}

func (x *UpdateMigrationRequest) GetDownSql() string {
	if x != nil && x.DownSql != nil {
		return *x.DownSql
	}
	return ""
}

func (x *UpdateMigrationRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type UpdateMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Migration *Migration `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
}

func (x *UpdateMigrationResponse) Reset() {
	*x = UpdateMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMigrationResponse) ProtoMessage() {}

func (x *UpdateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMigrationResponse.ProtoReflect.Descriptor instead.
func (*UpdateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type DeleteMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMigrationRequest) Reset() {
	*x = DeleteMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMigrationRequest) ProtoMessage() {}

func (x *DeleteMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMigrationRequest.ProtoReflect.Descriptor instead.
func (*DeleteMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMigrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMigrationResponse) Reset() {
	*x = DeleteMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMigrationResponse) ProtoMessage() {}

func (x *DeleteMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMigrationResponse.ProtoReflect.Descriptor instead.
func (*DeleteMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{13}
}

type ExecuteMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MigrationId  string `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
}

func (x *ExecuteMigrationRequest) Reset() {
	*x = ExecuteMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMigrationRequest) ProtoMessage() {}

func (x *ExecuteMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMigrationRequest.ProtoReflect.Descriptor instead.
func (*ExecuteMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteMigrationRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *ExecuteMigrationRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type ExecuteMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Run *MigrationRun `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
}

func (x *ExecuteMigrationResponse) Reset() {
	*x = ExecuteMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMigrationResponse) ProtoMessage() {}

func (x *ExecuteMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMigrationResponse.ProtoReflect.Descriptor instead.
func (*ExecuteMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteMigrationResponse) GetRun() *MigrationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type WatchMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
}

func (x *WatchMigrationRequest) Reset() {
	*x = WatchMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMigrationRequest) ProtoMessage() {}

func (x *WatchMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMigrationRequest.ProtoReflect.Descriptor instead.
func (*WatchMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{16}
}

func (x *WatchMigrationRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RollbackMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
}

func (x *RollbackMigrationRequest) Reset() {
	*x = RollbackMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationRequest) ProtoMessage() {}

func (x *RollbackMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationRequest.ProtoReflect.Descriptor instead.
func (*RollbackMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{17}
}

func (x *RollbackMigrationRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RollbackMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Run *MigrationRun `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
}

func (x *RollbackMigrationResponse) Reset() {
	*x = RollbackMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationResponse) ProtoMessage() {}

func (x *RollbackMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationResponse.ProtoReflect.Descriptor instead.
func (*RollbackMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{18}
}

func (x *RollbackMigrationResponse) GetRun() *MigrationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type WatchRollbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
}

func (x *WatchRollbackRequest) Reset() {
	*x = WatchRollbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchRollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRollbackRequest) ProtoMessage() {}

func (x *WatchRollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRollbackRequest.ProtoReflect.Descriptor instead.
func (*WatchRollbackRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{19}
}

func (x *WatchRollbackRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ValidateMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpSql   string `protobuf:"bytes,1,opt,name=up_sql,json=upSql,proto3" json:"up_sql,omitempty"`
	DownSql string `protobuf:"bytes,2,opt,name=down_sql,json=downSql,proto3" json:"down_sql,omitempty"`
}

func (x *ValidateMigrationRequest) Reset() {
	*x = ValidateMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMigrationRequest) ProtoMessage() {}

func (x *ValidateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMigrationRequest.ProtoReflect.Descriptor instead.
func (*ValidateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{20}
}

func (x *ValidateMigrationRequest) GetUpSql() string {
	if x != nil {
		return x.UpSql
	}
	return ""
}

func (x *ValidateMigrationRequest) GetDownSql() string {
	if x != nil {
		return x.DownSql
	}
	return ""
}

type ValidateMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid  bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ValidateMigrationResponse) Reset() {
	*x = ValidateMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMigrationResponse) ProtoMessage() {}

func (x *ValidateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMigrationResponse.ProtoReflect.Descriptor instead.
func (*ValidateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{21}
}

func (x *ValidateMigrationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateMigrationResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DryRunMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MigrationId  string `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
}

func (x *DryRunMigrationRequest) Reset() {
	*x = DryRunMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DryRunMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunMigrationRequest) ProtoMessage() {}

func (x *DryRunMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunMigrationRequest.ProtoReflect.Descriptor instead.
func (*DryRunMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{22}
}

func (x *DryRunMigrationRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *DryRunMigrationRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type DryRunMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid    bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors   []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings []string `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
}

func (x *DryRunMigrationResponse) Reset() {
	*x = DryRunMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DryRunMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunMigrationResponse) ProtoMessage() {}

func (x *DryRunMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunMigrationResponse.ProtoReflect.Descriptor instead.
func (*DryRunMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{23}
}

func (x *DryRunMigrationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *DryRunMigrationResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *DryRunMigrationResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type GetMigrationRunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMigrationRunRequest) Reset() {
	*x = GetMigrationRunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMigrationRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationRunRequest) ProtoMessage() {}

func (x *GetMigrationRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationRunRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationRunRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{24}
}

func (x *GetMigrationRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMigrationRunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Run *MigrationRun `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
}

func (x *GetMigrationRunResponse) Reset() {
	*x = GetMigrationRunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMigrationRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationRunResponse) ProtoMessage() {}

func (x *GetMigrationRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationRunResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationRunResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{25}
}

func (x *GetMigrationRunResponse) GetRun() *MigrationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListMigrationRunsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MigrationId string `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Cursor      string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize    int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListMigrationRunsRequest) Reset() {
	*x = ListMigrationRunsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMigrationRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationRunsRequest) ProtoMessage() {}

func (x *ListMigrationRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationRunsRequest.ProtoReflect.Descriptor instead.
func (*ListMigrationRunsRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{26}
}

func (x *ListMigrationRunsRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *ListMigrationRunsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMigrationRunsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMigrationRunsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runs       []*MigrationRun `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextCursor string          `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	TotalCount int32           `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListMigrationRunsResponse) Reset() {
	*x = ListMigrationRunsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMigrationRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationRunsResponse) ProtoMessage() {}

func (x *ListMigrationRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationRunsResponse.ProtoReflect.Descriptor instead.
func (*ListMigrationRunsResponse) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{27}
}

func (x *ListMigrationRunsResponse) GetRuns() []*MigrationRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListMigrationRunsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListMigrationRunsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetMigrationLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
}

func (x *GetMigrationLogsRequest) Reset() {
	*x = GetMigrationLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_v1_migration_messages_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMigrationLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationLogsRequest) ProtoMessage() {}

func (x *GetMigrationLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_v1_migration_messages_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationLogsRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationLogsRequest) Descriptor() ([]byte, []int) {
	return file_migration_v1_migration_messages_proto_rawDescGZIP(), []int{28}
}

func (x *GetMigrationLogsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_migration_v1_migration_messages_proto protoreflect.FileDescriptor

var file_migration_v1_migration_messages_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x68,
	0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22,
	0xcf, 0x02, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15,
	0x0a, 0x06, 0x75, 0x70, 0x5f, 0x73, 0x71, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x75, 0x70, 0x53, 0x71, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x71,
	0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x77, 0x6e, 0x53, 0x71, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0xe4, 0x02, 0x0a, 0x0c, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xcb, 0x01, 0x0a, 0x11, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x6f, 0x77, 0x73, 0x5f, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x6f, 0x77, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xf9, 0x02, 0x0a, 0x16, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x29,
	0x0a, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x31, 0x0a, 0x14, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x11,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6c, 0x61, 0x70,
	0x73, 0x65, 0x64, 0x5f, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x6c,
	0x61, 0x70, 0x73, 0x65, 0x64, 0x4d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x44, 0x0a, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x4c,
	0x6f, 0x67, 0x22, 0xbb, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06,
	0x75, 0x70, 0x5f, 0x73, 0x71, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x70,
	0x53, 0x71, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x71, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x77, 0x6e, 0x53, 0x71, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x5a, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x16, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f,
	0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65,
	0x78, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x80, 0x02, 0x0a, 0x16, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x06, 0x75, 0x70, 0x5f, 0x73, 0x71, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x75, 0x70, 0x53, 0x71, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x71, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x07, 0x64, 0x6f, 0x77, 0x6e, 0x53, 0x71, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75, 0x70,
	0x5f, 0x73, 0x71, 0x6c, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x71,
	0x6c, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5a, 0x0a, 0x17,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x61, 0x0a,
	0x17, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x52, 0x0a, 0x18, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x03,
	0x72, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x52,
	0x03, 0x72, 0x75, 0x6e, 0x22, 0x2e, 0x0a, 0x15, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x75, 0x6e, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x18, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x19, 0x52, 0x6f, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x03, 0x72, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x22, 0x2d, 0x0a, 0x14,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x18, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x75, 0x70, 0x5f, 0x73, 0x71,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x70, 0x53, 0x71, 0x6c, 0x12, 0x19,
	0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x71, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x6f, 0x77, 0x6e, 0x53, 0x71, 0x6c, 0x22, 0x49, 0x0a, 0x19, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x22, 0x60, 0x0a, 0x16, 0x44, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x17, 0x44, 0x72, 0x79, 0x52, 0x75, 0x6e,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x51, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x36, 0x0a, 0x03, 0x72, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x75, 0x6e, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x22, 0x72, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x97, 0x01, 0x0a,
	0x19, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x72, 0x75,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x52, 0x04,
	0x72, 0x75, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x68, 0x75, 0x62,
	0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_migration_v1_migration_messages_proto_rawDescOnce sync.Once
	file_migration_v1_migration_messages_proto_rawDescData = file_migration_v1_migration_messages_proto_rawDesc
)

func file_migration_v1_migration_messages_proto_rawDescGZIP() []byte {
	file_migration_v1_migration_messages_proto_rawDescOnce.Do(func() {
		file_migration_v1_migration_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_migration_v1_migration_messages_proto_rawDescData)
	})
	return file_migration_v1_migration_messages_proto_rawDescData
}

var file_migration_v1_migration_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_migration_v1_migration_messages_proto_goTypes = []any{
	(*Migration)(nil),                 // 0: schemahub.migration.v1.Migration
	(*MigrationRun)(nil),              // 1: schemahub.migration.v1.MigrationRun
	(*MigrationLogEntry)(nil),         // 2: schemahub.migration.v1.MigrationLogEntry
	(*MigrationStatusMessage)(nil),    // 3: schemahub.migration.v1.MigrationStatusMessage
	(*CreateMigrationRequest)(nil),    // 4: schemahub.migration.v1.CreateMigrationRequest
	(*CreateMigrationResponse)(nil),   // 5: schemahub.migration.v1.CreateMigrationResponse
	(*GetMigrationRequest)(nil),       // 6: schemahub.migration.v1.GetMigrationRequest
	(*GetMigrationResponse)(nil),      // 7: schemahub.migration.v1.GetMigrationResponse
	(*ListMigrationsRequest)(nil),     // 8: schemahub.migration.v1.ListMigrationsRequest
	(*ListMigrationsResponse)(nil),    // 9: schemahub.migration.v1.ListMigrationsResponse
	(*UpdateMigrationRequest)(nil),    // 10: schemahub.migration.v1.UpdateMigrationRequest
	(*UpdateMigrationResponse)(nil),   // 11: schemahub.migration.v1.UpdateMigrationResponse
	(*DeleteMigrationRequest)(nil),    // 12: schemahub.migration.v1.DeleteMigrationRequest
	(*DeleteMigrationResponse)(nil),   // 13: schemahub.migration.v1.DeleteMigrationResponse
	(*ExecuteMigrationRequest)(nil),   // 14: schemahub.migration.v1.ExecuteMigrationRequest
	(*ExecuteMigrationResponse)(nil),  // 15: schemahub.migration.v1.ExecuteMigrationResponse
	(*WatchMigrationRequest)(nil),     // 16: schemahub.migration.v1.WatchMigrationRequest
	(*RollbackMigrationRequest)(nil),  // 17: schemahub.migration.v1.RollbackMigrationRequest
	(*RollbackMigrationResponse)(nil), // 18: schemahub.migration.v1.RollbackMigrationResponse
	(*WatchRollbackRequest)(nil),      // 19: schemahub.migration.v1.WatchRollbackRequest
	(*ValidateMigrationRequest)(nil),  // 20: schemahub.migration.v1.ValidateMigrationRequest
	(*ValidateMigrationResponse)(nil), // 21: schemahub.migration.v1.ValidateMigrationResponse
	(*DryRunMigrationRequest)(nil),    // 22: schemahub.migration.v1.DryRunMigrationRequest
	(*DryRunMigrationResponse)(nil),   // 23: schemahub.migration.v1.DryRunMigrationResponse
	(*GetMigrationRunRequest)(nil),    // 24: schemahub.migration.v1.GetMigrationRunRequest
	(*GetMigrationRunResponse)(nil),   // 25: schemahub.migration.v1.GetMigrationRunResponse
	(*ListMigrationRunsRequest)(nil),  // 26: schemahub.migration.v1.ListMigrationRunsRequest
	(*ListMigrationRunsResponse)(nil), // 27: schemahub.migration.v1.ListMigrationRunsResponse
	(*GetMigrationLogsRequest)(nil),   // 28: schemahub.migration.v1.GetMigrationLogsRequest
}
var file_migration_v1_migration_messages_proto_depIdxs = []int32{
	2, // 0: schemahub.migration.v1.MigrationStatusMessage.last_log:type_name -> schemahub.migration.v1.MigrationLogEntry
	0, // 1: schemahub.migration.v1.CreateMigrationResponse.migration:type_name -> schemahub.migration.v1.Migration
	0, // 2: schemahub.migration.v1.GetMigrationResponse.migration:type_name -> schemahub.migration.v1.Migration
	0, // 3: schemahub.migration.v1.ListMigrationsResponse.migrations:type_name -> schemahub.migration.v1.Migration
	0, // 4: schemahub.migration.v1.UpdateMigrationResponse.migration:type_name -> schemahub.migration.v1.Migration
	1, // 5: schemahub.migration.v1.ExecuteMigrationResponse.run:type_name -> schemahub.migration.v1.MigrationRun
	1, // 6: schemahub.migration.v1.RollbackMigrationResponse.run:type_name -> schemahub.migration.v1.MigrationRun
	1, // 7: schemahub.migration.v1.GetMigrationRunResponse.run:type_name -> schemahub.migration.v1.MigrationRun
	1, // 8: schemahub.migration.v1.ListMigrationRunsResponse.runs:type_name -> schemahub.migration.v1.MigrationRun
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_migration_v1_migration_messages_proto_init() }
func file_migration_v1_migration_messages_proto_init() {
	if File_migration_v1_migration_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_migration_v1_migration_messages_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Migration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MigrationRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MigrationLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MigrationStatusMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListMigrationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListMigrationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ExecuteMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ExecuteMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*WatchMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*RollbackMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*RollbackMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*WatchRollbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*ValidateMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*ValidateMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*DryRunMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*DryRunMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*GetMigrationRunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*GetMigrationRunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*ListMigrationRunsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*ListMigrationRunsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_v1_migration_messages_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*GetMigrationLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_migration_v1_migration_messages_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_migration_v1_migration_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migration_v1_migration_messages_proto_goTypes,
		DependencyIndexes: file_migration_v1_migration_messages_proto_depIdxs,
		MessageInfos:      file_migration_v1_migration_messages_proto_msgTypes,
	}.Build()
	File_migration_v1_migration_messages_proto = out.File
	file_migration_v1_migration_messages_proto_rawDesc = nil
	file_migration_v1_migration_messages_proto_goTypes = nil
	file_migration_v1_migration_messages_proto_depIdxs = nil
}
