// Code generated by protoc-gen-go. DO NOT EDIT.
// Source: proto/auth/v1/auth_service.proto

package authv1

import (
	commonv1 "github.com/schemahub/backend/proto/common/v1"
)

// ── Messages ──

type RegisterRequest struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"display_name"`
}

type RegisterResponse struct {
	User         *commonv1.User `json:"user"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresIn    int32          `json:"expires_in"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	User         *commonv1.User `json:"user"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresIn    int32          `json:"expires_in"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int32  `json:"expires_in"`
}

type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type LogoutResponse struct{}

type GetCurrentUserRequest struct{}

type GetCurrentUserResponse struct {
	User *commonv1.User `json:"user"`
}

type UpdateUserRequest struct {
	DisplayName string `json:"display_name"`
	AvatarURL   string `json:"avatar_url"`
}

type UpdateUserResponse struct {
	User *commonv1.User `json:"user"`
}

type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

type ChangePasswordResponse struct{}

type OAuthIdentity struct {
	ID            string `json:"id"`
	Provider      string `json:"provider"`
	ProviderEmail string `json:"provider_email"`
	CreatedAt     string `json:"created_at"`
	LastUsedAt    string `json:"last_used_at"`
}

type GetOAuthURLRequest struct {
	Provider   string `json:"provider"`
	RedirectTo string `json:"redirect_to"`
	Linking    bool   `json:"linking"`
}

type GetOAuthURLResponse struct {
	AuthURL    string `json:"auth_url"`
	StateToken string `json:"state_token"`
}

type HandleOAuthCallbackRequest struct {
	Provider     string `json:"provider"`
	Code         string `json:"code"`
	State        string `json:"state"`
	CodeVerifier string `json:"code_verifier"`
}

type HandleOAuthCallbackResponse struct {
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresIn    int32          `json:"expires_in"`
	User         *commonv1.User `json:"user"`
	IsNewUser    bool           `json:"is_new_user"`
	NeedsLinking bool           `json:"needs_linking"`
}

type LinkOAuthIdentityRequest struct {
	Provider string `json:"provider"`
	Code     string `json:"code"`
	State    string `json:"state"`
}

type LinkOAuthIdentityResponse struct{}

type UnlinkOAuthIdentityRequest struct {
	Provider string `json:"provider"`
}

type UnlinkOAuthIdentityResponse struct{}

type SendVerificationEmailRequest struct {
	Email string `json:"email"`
}

type SendVerificationEmailResponse struct{}

type VerifyEmailRequest struct {
	Token string `json:"token"`
}

type VerifyEmailResponse struct{}

type DeleteAccountRequest struct {
	Password string `json:"password"`
}

type DeleteAccountResponse struct{}

type ForgotPasswordRequest struct {
	Email string `json:"email"`
}

type ForgotPasswordResponse struct{}

type ResetPasswordRequest struct {
	Token    string `json:"token"`
	Password string `json:"password"`
}

type ResetPasswordResponse struct{}

type ListLinkedIdentitiesRequest struct{}

type ListLinkedIdentitiesResponse struct {
	Identities []*OAuthIdentity `json:"identities"`
}


