// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: drift/v1/drift_service.proto

package driftv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DriftService_CheckDrift_FullMethodName        = "/schemahub.drift.v1.DriftService/CheckDrift"
	DriftService_ListDriftEvents_FullMethodName   = "/schemahub.drift.v1.DriftService/ListDriftEvents"
	DriftService_GetDriftEvent_FullMethodName     = "/schemahub.drift.v1.DriftService/GetDriftEvent"
	DriftService_ResolveDriftEvent_FullMethodName = "/schemahub.drift.v1.DriftService/ResolveDriftEvent"
	DriftService_GetDriftStats_FullMethodName     = "/schemahub.drift.v1.DriftService/GetDriftStats"
)

// DriftServiceClient is the client API for DriftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriftServiceClient interface {
	CheckDrift(ctx context.Context, in *CheckDriftRequest, opts ...grpc.CallOption) (*CheckDriftResponse, error)
	ListDriftEvents(ctx context.Context, in *ListDriftEventsRequest, opts ...grpc.CallOption) (*ListDriftEventsResponse, error)
	GetDriftEvent(ctx context.Context, in *GetDriftEventRequest, opts ...grpc.CallOption) (*GetDriftEventResponse, error)
	ResolveDriftEvent(ctx context.Context, in *ResolveDriftEventRequest, opts ...grpc.CallOption) (*ResolveDriftEventResponse, error)
	GetDriftStats(ctx context.Context, in *GetDriftStatsRequest, opts ...grpc.CallOption) (*GetDriftStatsResponse, error)
}

type driftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriftServiceClient(cc grpc.ClientConnInterface) DriftServiceClient {
	return &driftServiceClient{cc}
}

func (c *driftServiceClient) CheckDrift(ctx context.Context, in *CheckDriftRequest, opts ...grpc.CallOption) (*CheckDriftResponse, error) {
	out := new(CheckDriftResponse)
	err := c.cc.Invoke(ctx, DriftService_CheckDrift_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftServiceClient) ListDriftEvents(ctx context.Context, in *ListDriftEventsRequest, opts ...grpc.CallOption) (*ListDriftEventsResponse, error) {
	out := new(ListDriftEventsResponse)
	err := c.cc.Invoke(ctx, DriftService_ListDriftEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftServiceClient) GetDriftEvent(ctx context.Context, in *GetDriftEventRequest, opts ...grpc.CallOption) (*GetDriftEventResponse, error) {
	out := new(GetDriftEventResponse)
	err := c.cc.Invoke(ctx, DriftService_GetDriftEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftServiceClient) ResolveDriftEvent(ctx context.Context, in *ResolveDriftEventRequest, opts ...grpc.CallOption) (*ResolveDriftEventResponse, error) {
	out := new(ResolveDriftEventResponse)
	err := c.cc.Invoke(ctx, DriftService_ResolveDriftEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftServiceClient) GetDriftStats(ctx context.Context, in *GetDriftStatsRequest, opts ...grpc.CallOption) (*GetDriftStatsResponse, error) {
	out := new(GetDriftStatsResponse)
	err := c.cc.Invoke(ctx, DriftService_GetDriftStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriftServiceServer is the server API for DriftService service.
// All implementations must embed UnimplementedDriftServiceServer
// for forward compatibility
type DriftServiceServer interface {
	CheckDrift(context.Context, *CheckDriftRequest) (*CheckDriftResponse, error)
	ListDriftEvents(context.Context, *ListDriftEventsRequest) (*ListDriftEventsResponse, error)
	GetDriftEvent(context.Context, *GetDriftEventRequest) (*GetDriftEventResponse, error)
	ResolveDriftEvent(context.Context, *ResolveDriftEventRequest) (*ResolveDriftEventResponse, error)
	GetDriftStats(context.Context, *GetDriftStatsRequest) (*GetDriftStatsResponse, error)
	mustEmbedUnimplementedDriftServiceServer()
}

// UnimplementedDriftServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDriftServiceServer struct {
}

func (UnimplementedDriftServiceServer) CheckDrift(context.Context, *CheckDriftRequest) (*CheckDriftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDrift not implemented")
}
func (UnimplementedDriftServiceServer) ListDriftEvents(context.Context, *ListDriftEventsRequest) (*ListDriftEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDriftEvents not implemented")
}
func (UnimplementedDriftServiceServer) GetDriftEvent(context.Context, *GetDriftEventRequest) (*GetDriftEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDriftEvent not implemented")
}
func (UnimplementedDriftServiceServer) ResolveDriftEvent(context.Context, *ResolveDriftEventRequest) (*ResolveDriftEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveDriftEvent not implemented")
}
func (UnimplementedDriftServiceServer) GetDriftStats(context.Context, *GetDriftStatsRequest) (*GetDriftStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDriftStats not implemented")
}
func (UnimplementedDriftServiceServer) mustEmbedUnimplementedDriftServiceServer() {}

// UnsafeDriftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriftServiceServer will
// result in compilation errors.
type UnsafeDriftServiceServer interface {
	mustEmbedUnimplementedDriftServiceServer()
}

func RegisterDriftServiceServer(s grpc.ServiceRegistrar, srv DriftServiceServer) {
	s.RegisterService(&DriftService_ServiceDesc, srv)
}

func _DriftService_CheckDrift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDriftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftServiceServer).CheckDrift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriftService_CheckDrift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftServiceServer).CheckDrift(ctx, req.(*CheckDriftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriftService_ListDriftEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriftEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftServiceServer).ListDriftEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriftService_ListDriftEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftServiceServer).ListDriftEvents(ctx, req.(*ListDriftEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriftService_GetDriftEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriftEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftServiceServer).GetDriftEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriftService_GetDriftEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftServiceServer).GetDriftEvent(ctx, req.(*GetDriftEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriftService_ResolveDriftEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDriftEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftServiceServer).ResolveDriftEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriftService_ResolveDriftEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftServiceServer).ResolveDriftEvent(ctx, req.(*ResolveDriftEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriftService_GetDriftStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriftStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftServiceServer).GetDriftStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriftService_GetDriftStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftServiceServer).GetDriftStats(ctx, req.(*GetDriftStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriftService_ServiceDesc is the grpc.ServiceDesc for DriftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schemahub.drift.v1.DriftService",
	HandlerType: (*DriftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDrift",
			Handler:    _DriftService_CheckDrift_Handler,
		},
		{
			MethodName: "ListDriftEvents",
			Handler:    _DriftService_ListDriftEvents_Handler,
		},
		{
			MethodName: "GetDriftEvent",
			Handler:    _DriftService_GetDriftEvent_Handler,
		},
		{
			MethodName: "ResolveDriftEvent",
			Handler:    _DriftService_ResolveDriftEvent_Handler,
		},
		{
			MethodName: "GetDriftStats",
			Handler:    _DriftService_GetDriftStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drift/v1/drift_service.proto",
}
