// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: schema/v1/schema_service.proto

package schemav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchemaService_IntrospectSchema_FullMethodName      = "/schemahub.schema.v1.SchemaService/IntrospectSchema"
	SchemaService_GetSchema_FullMethodName             = "/schemahub.schema.v1.SchemaService/GetSchema"
	SchemaService_ListSchemas_FullMethodName           = "/schemahub.schema.v1.SchemaService/ListSchemas"
	SchemaService_ListSchemaVersions_FullMethodName    = "/schemahub.schema.v1.SchemaService/ListSchemaVersions"
	SchemaService_GetSchemaVersion_FullMethodName      = "/schemahub.schema.v1.SchemaService/GetSchemaVersion"
	SchemaService_CompareSchemaVersions_FullMethodName = "/schemahub.schema.v1.SchemaService/CompareSchemaVersions"
	SchemaService_ListSchemaObjects_FullMethodName     = "/schemahub.schema.v1.SchemaService/ListSchemaObjects"
	SchemaService_GetSchemaDiagram_FullMethodName      = "/schemahub.schema.v1.SchemaService/GetSchemaDiagram"
)

// SchemaServiceClient is the client API for SchemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchemaServiceClient interface {
	IntrospectSchema(ctx context.Context, in *IntrospectSchemaRequest, opts ...grpc.CallOption) (*IntrospectSchemaResponse, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	ListSchemaVersions(ctx context.Context, in *ListSchemaVersionsRequest, opts ...grpc.CallOption) (*ListSchemaVersionsResponse, error)
	GetSchemaVersion(ctx context.Context, in *GetSchemaVersionRequest, opts ...grpc.CallOption) (*GetSchemaVersionResponse, error)
	CompareSchemaVersions(ctx context.Context, in *CompareSchemaVersionsRequest, opts ...grpc.CallOption) (*CompareSchemaVersionsResponse, error)
	ListSchemaObjects(ctx context.Context, in *ListSchemaObjectsRequest, opts ...grpc.CallOption) (*ListSchemaObjectsResponse, error)
	GetSchemaDiagram(ctx context.Context, in *GetSchemaDiagramRequest, opts ...grpc.CallOption) (*GetSchemaDiagramResponse, error)
}

type schemaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemaServiceClient(cc grpc.ClientConnInterface) SchemaServiceClient {
	return &schemaServiceClient{cc}
}

func (c *schemaServiceClient) IntrospectSchema(ctx context.Context, in *IntrospectSchemaRequest, opts ...grpc.CallOption) (*IntrospectSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntrospectSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_IntrospectSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, SchemaService_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ListSchemaVersions(ctx context.Context, in *ListSchemaVersionsRequest, opts ...grpc.CallOption) (*ListSchemaVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemaVersionsResponse)
	err := c.cc.Invoke(ctx, SchemaService_ListSchemaVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) GetSchemaVersion(ctx context.Context, in *GetSchemaVersionRequest, opts ...grpc.CallOption) (*GetSchemaVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaVersionResponse)
	err := c.cc.Invoke(ctx, SchemaService_GetSchemaVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) CompareSchemaVersions(ctx context.Context, in *CompareSchemaVersionsRequest, opts ...grpc.CallOption) (*CompareSchemaVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareSchemaVersionsResponse)
	err := c.cc.Invoke(ctx, SchemaService_CompareSchemaVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ListSchemaObjects(ctx context.Context, in *ListSchemaObjectsRequest, opts ...grpc.CallOption) (*ListSchemaObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemaObjectsResponse)
	err := c.cc.Invoke(ctx, SchemaService_ListSchemaObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) GetSchemaDiagram(ctx context.Context, in *GetSchemaDiagramRequest, opts ...grpc.CallOption) (*GetSchemaDiagramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaDiagramResponse)
	err := c.cc.Invoke(ctx, SchemaService_GetSchemaDiagram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServiceServer is the server API for SchemaService service.
// All implementations must embed UnimplementedSchemaServiceServer
// for forward compatibility.
type SchemaServiceServer interface {
	IntrospectSchema(context.Context, *IntrospectSchemaRequest) (*IntrospectSchemaResponse, error)
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	ListSchemaVersions(context.Context, *ListSchemaVersionsRequest) (*ListSchemaVersionsResponse, error)
	GetSchemaVersion(context.Context, *GetSchemaVersionRequest) (*GetSchemaVersionResponse, error)
	CompareSchemaVersions(context.Context, *CompareSchemaVersionsRequest) (*CompareSchemaVersionsResponse, error)
	ListSchemaObjects(context.Context, *ListSchemaObjectsRequest) (*ListSchemaObjectsResponse, error)
	GetSchemaDiagram(context.Context, *GetSchemaDiagramRequest) (*GetSchemaDiagramResponse, error)
	mustEmbedUnimplementedSchemaServiceServer()
}

// UnimplementedSchemaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchemaServiceServer struct{}

func (UnimplementedSchemaServiceServer) IntrospectSchema(context.Context, *IntrospectSchemaRequest) (*IntrospectSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IntrospectSchema not implemented")
}
func (UnimplementedSchemaServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedSchemaServiceServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedSchemaServiceServer) ListSchemaVersions(context.Context, *ListSchemaVersionsRequest) (*ListSchemaVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemaVersions not implemented")
}
func (UnimplementedSchemaServiceServer) GetSchemaVersion(context.Context, *GetSchemaVersionRequest) (*GetSchemaVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchemaVersion not implemented")
}
func (UnimplementedSchemaServiceServer) CompareSchemaVersions(context.Context, *CompareSchemaVersionsRequest) (*CompareSchemaVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareSchemaVersions not implemented")
}
func (UnimplementedSchemaServiceServer) ListSchemaObjects(context.Context, *ListSchemaObjectsRequest) (*ListSchemaObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemaObjects not implemented")
}
func (UnimplementedSchemaServiceServer) GetSchemaDiagram(context.Context, *GetSchemaDiagramRequest) (*GetSchemaDiagramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchemaDiagram not implemented")
}
func (UnimplementedSchemaServiceServer) mustEmbedUnimplementedSchemaServiceServer() {}
func (UnimplementedSchemaServiceServer) testEmbeddedByValue()                       {}

// UnsafeSchemaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemaServiceServer will
// result in compilation errors.
type UnsafeSchemaServiceServer interface {
	mustEmbedUnimplementedSchemaServiceServer()
}

func RegisterSchemaServiceServer(s grpc.ServiceRegistrar, srv SchemaServiceServer) {
	// If the following call panics, it indicates UnimplementedSchemaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchemaService_ServiceDesc, srv)
}

func _SchemaService_IntrospectSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).IntrospectSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_IntrospectSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).IntrospectSchema(ctx, req.(*IntrospectSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ListSchemaVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemaVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ListSchemaVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ListSchemaVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ListSchemaVersions(ctx, req.(*ListSchemaVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_GetSchemaVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).GetSchemaVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_GetSchemaVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).GetSchemaVersion(ctx, req.(*GetSchemaVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_CompareSchemaVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareSchemaVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).CompareSchemaVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_CompareSchemaVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).CompareSchemaVersions(ctx, req.(*CompareSchemaVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ListSchemaObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemaObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ListSchemaObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ListSchemaObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ListSchemaObjects(ctx, req.(*ListSchemaObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_GetSchemaDiagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).GetSchemaDiagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_GetSchemaDiagram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).GetSchemaDiagram(ctx, req.(*GetSchemaDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchemaService_ServiceDesc is the grpc.ServiceDesc for SchemaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchemaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schemahub.schema.v1.SchemaService",
	HandlerType: (*SchemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IntrospectSchema",
			Handler:    _SchemaService_IntrospectSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _SchemaService_GetSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _SchemaService_ListSchemas_Handler,
		},
		{
			MethodName: "ListSchemaVersions",
			Handler:    _SchemaService_ListSchemaVersions_Handler,
		},
		{
			MethodName: "GetSchemaVersion",
			Handler:    _SchemaService_GetSchemaVersion_Handler,
		},
		{
			MethodName: "CompareSchemaVersions",
			Handler:    _SchemaService_CompareSchemaVersions_Handler,
		},
		{
			MethodName: "ListSchemaObjects",
			Handler:    _SchemaService_ListSchemaObjects_Handler,
		},
		{
			MethodName: "GetSchemaDiagram",
			Handler:    _SchemaService_GetSchemaDiagram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema/v1/schema_service.proto",
}
